apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: config-my-consul-api
data:
  application.yml: |+
    spring:
      config:
        import: consul:consul-server.default:8500
      cloud:
        consul:
          host: consul-server.default
          port: 8500
          config:
            enabled: true
            defaultContext: config
            data-key: data
            profileSeparator: '::'
            format: yaml
            prefixes:
              - product
              - connect
          discovery:
            instanceId: ${spring.application.name}:${random.value}
      application:
        name: my-consul-api-k8s
    server:
      port: 8080